### ISSUE TITLE
Correct grammatical errors in index.html

### ISSUE THREAD

**Issue by NithurjanA** [mdmdni/portfolio-page#1]
The text in the index.html contains some grammatical errors that need to be adjusted. Below are some examples:

- vielseitige Kompetenzen." -> "vielseitigen Kompetenzen.
- Diese vielseitigen Rollen haben mir ermöglicht -> Diese vielseitigen Rollen haben es mir ermöglicht
- eine hohe Effizienz aus, wobei ich stets darauf bedacht bin -> eine hohe Effizienz aus. Dabei bin ich stets darauf bedacht

**Comment by mdmdni** [comment]
@NithurjanA thank you for your contribution!
